image:
  file: .gitpod.Dockerfile

tasks:
  - before: npm install -g firebase firebase-tools
  - init: yarn install && yarn run build && cd functions && yarn install && cd ..
    command: yarn run start
